### ISSUE TITLE
Hardware Virtualization on Nested ESXi.

### ISSUE THREAD

**Issue by aredan** [DemitasseNZ/vSphereAutoLab#31]
Maybe is just my setup, now I'm running AutoLab on ESXi 6 + vCenter on a Dell R710, while installing ESXi on Lab_Host2 it says that there wasn't any Hardware Virtualization support. With VM hardware in version 8 the option is grayed out ( https://www.dropbox.com/s/wpce262cwp8uiku/no-virt.support_Lab_Host2.jpg?dl=0 ), after upgrade VM hardware to version 11 is available ( https://www.dropbox.com/s/g529w71v7o42z4s/with-virt.support_Lab_Host2.jpg?dl=0 ).

I will try with others VM hardware version and see with one the option is available.

**Comment by nathcoad** [comment]
Hardware version 9 (ESXi 5.1) is the earliest that the hardware virtualization support can be enabled from the web client.

Perhaps the VMs in the ovf could be updated to hardware version 9 and the setting enabled?  I doubt many people would be deploying onto ESXi 5 or older.

**Comment by DemitasseNZ** [comment]
Upgraded Workstation VMs to hardware 9
Need to apply same update to ESXi builds

**Comment by DemitasseNZ** [comment]
Updated Workstation VMs to Workstation 10 minimum, ESXi 5.5

**Comment by DemitasseNZ** [comment]
Updated ESXi VMs, setting is respected by OVF export/import
