### ISSUE TITLE
pfSense router

### ISSUE THREAD

**Issue by DemitasseNZ** [DemitasseNZ/vSphereAutoLab#5]
uild a pfSense VM as drop in replacement for FreeSCO
Also include routing for SRM
Or possible Floppy Firewall
http://www.zelow.no/floppyfw/

**Comment by aredan** [comment]
I getting information about spinning a new pfSense VM and inject a pre-build configuration. I'll let you know my findings.

**Comment by DemitasseNZ** [comment]
Merging this intent into the Windows free build.
https://github.com/DemitasseNZ/vSphereAutoLab/issues/41
